<#
.SYNOPSIS
    Manage the skill library of reusable scripts (sdf-flow\library): find, lint, add,
    update, check integrity, export to another copy of the skills, remove.

.DESCRIPTION
    Actions
      List     show every registered script
      Find     search the registry (-Query "words"); exit 0 when something matches
      Lint     check a candidate script (-Path); exit 1 on errors
      Add      register a new script: needs -Path -Purpose -Test -ApprovedBy (and honest flags)
      Update   replace a registered script with a new version: needs -Id -Path -ApprovedBy
      Check    verify that every registered file still has its recorded SHA-256; exit 1 on
               MODIFIED, MISSING or UNREGISTERED files. Run it before running library scripts.
      Test     run the self-test of one entry (-Id) or of all: the entry's Test text holds the
               arguments that make the script test itself and exit 0 (for example -Selftest)
      Export   copy one entry to another copy of sdf-flow (-Id, -Dest <...\sdf-flow>)
      Remove   unregister and delete a script: needs -Id -ApprovedBy

    The registry is library\index.json (source of truth); library\INDEX.md is regenerated.
    After Add, Update, Remove and Export the library is mirrored to the sibling tool tree
    (.claude and .agents) when both exist, unless -NoMirror is given.

    -ApprovedBy must quote the user's approval and the date, or "policy:auto, <date>" when
    the user opted in to automatic saving. The automatic policy is refused for scripts that
    use the network, write outside the project, are destructive or need administrator rights.

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File sdf-library.ps1 -Action Find -Query "memory android"
    powershell -NoProfile -ExecutionPolicy Bypass -File sdf-library.ps1 -Action Add -Path .\pack.ps1 -Purpose "Zip a release folder with a manifest" -Steps "7" -Platforms windows -Tags "package,release" -Test "-Selftest" -Source MyApp -ApprovedBy "user, 2026-10-09: ok save it"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][ValidateSet('List', 'Find', 'Lint', 'Add', 'Update', 'Check', 'Test', 'Export', 'Remove')][string]$Action,
    [string]$Path = '',
    [string]$Id = '',
    [string]$Query = '',
    [string]$Name = '',
    [string]$Purpose = '',
    [string]$Steps = '',
    [string]$Platforms = 'windows',
    [string]$Tags = '',
    [string]$Test = '',
    [string]$Source = '',
    [string]$ApprovedBy = '',
    [string]$Version = '',
    [string]$Dest = '',
    [switch]$Network,
    [switch]$WritesOutside,
    [switch]$Destructive,
    [switch]$NeedsAdmin,
    [switch]$NoMirror,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$utf8 = New-Object System.Text.UTF8Encoding($false)
$skillRoot = Split-Path -Parent $PSScriptRoot

function Get-Lib([string]$root) {
    $dir = Join-Path $root 'library'
    return @{ Root = $root; Dir = $dir; Scripts = (Join-Path $dir 'scripts'); Index = (Join-Path $dir 'index.json'); Md = (Join-Path $dir 'INDEX.md') }
}

function Split-List([string]$s) {
    return @($s -split '[,;]' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' })
}

function Read-Entries($lib) {
    if (-not (Test-Path -LiteralPath $lib.Index)) { return @() }
    $text = [System.IO.File]::ReadAllText($lib.Index, $utf8)
    if ($text.Trim() -eq '') { return @() }
    $data = $text | ConvertFrom-Json
    if ($data.entries) { return @($data.entries) }
    return @()
}

function Write-Entries($lib, $entries) {
    [void](New-Item -ItemType Directory -Path $lib.Scripts -Force)
    $obj = [pscustomobject]@{ version = 1; entries = @($entries) }
    [System.IO.File]::WriteAllText($lib.Index, ($obj | ConvertTo-Json -Depth 8), $utf8)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('# Skill library index')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('Generated by `scripts/sdf-library.ps1` from `index.json`. Do not edit by hand.')
    [void]$sb.AppendLine('Find a script with `-Action Find -Query "<need>"`; verify integrity with `-Action Check` before running one.')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('| ID | Script | Version | Platforms | Steps | Purpose | Flags | Test | Added |')
    [void]$sb.AppendLine('|---|---|---|---|---|---|---|---|---|')
    foreach ($e in $entries) {
        $f = @()
        if ($e.flags.network) { $f += 'network' }
        if ($e.flags.writesOutside) { $f += 'writes-outside' }
        if ($e.flags.destructive) { $f += 'destructive' }
        if ($e.flags.needsAdmin) { $f += 'admin' }
        if ($f.Count -eq 0) { $f = @('none') }
        $row = @($e.id, ('scripts/' + $e.file), $e.version, (@($e.platforms) -join ', '), (@($e.steps) -join ', '), $e.purpose, ($f -join ', '), ('`' + $e.test + '`'), $e.added)
        [void]$sb.AppendLine('| ' + (($row | ForEach-Object { ([string]$_).Replace('|', '/') }) -join ' | ') + ' |')
    }
    if (@($entries).Count -eq 0) { [void]$sb.AppendLine('| (empty) | | | | | | | | |') }
    [System.IO.File]::WriteAllText($lib.Md, $sb.ToString(), $utf8)
}

function Get-Hash([string]$file) { return (Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash.ToLower() }

function Sync-Mirror([string]$root) {
    if ($NoMirror) { return }
    if ((Split-Path -Leaf $root) -ne 'sdf-flow') { return }
    $skills = Split-Path -Parent $root
    if ((Split-Path -Leaf $skills) -ne 'skills') { return }
    $tree = Split-Path -Parent $skills
    $base = Split-Path -Parent $tree
    $treeName = Split-Path -Leaf $tree
    $other = $null
    if ($treeName -eq '.claude') { $other = Join-Path $base '.agents\skills\sdf-flow' }
    elseif ($treeName -eq '.agents') { $other = Join-Path $base '.claude\skills\sdf-flow' }
    if (-not $other -or -not (Test-Path -LiteralPath $other)) { return }
    $src = Join-Path $root 'library'
    $dst = Join-Path $other 'library'
    [void](New-Item -ItemType Directory -Path $dst -Force)
    $srcFiles = @(Get-ChildItem -LiteralPath $src -Recurse -File)
    foreach ($f in $srcFiles) {
        $rel = $f.FullName.Substring($src.Length + 1)
        $to = Join-Path $dst $rel
        [void](New-Item -ItemType Directory -Path (Split-Path -Parent $to) -Force)
        Copy-Item -LiteralPath $f.FullName -Destination $to -Force
    }
    foreach ($f in @(Get-ChildItem -LiteralPath $dst -Recurse -File)) {
        $rel = $f.FullName.Substring($dst.Length + 1)
        if (-not (Test-Path -LiteralPath (Join-Path $src $rel))) { Remove-Item -LiteralPath $f.FullName -Force }
    }
    "Mirrored the library to $other"
}

function Test-Script([string]$file, [hashtable]$declared) {
    $errors = New-Object System.Collections.ArrayList
    $warns = New-Object System.Collections.ArrayList
    $detected = @{ network = $false; destructive = $false; writesOutside = $false; needsAdmin = $false }
    if (-not (Test-Path -LiteralPath $file -PathType Leaf)) { [void]$errors.Add("file not found: $file"); return @{ Errors = @($errors); Warnings = @($warns); Detected = $detected } }
    $ext = [System.IO.Path]::GetExtension($file).ToLower()
    if (@('.ps1', '.sh', '.py') -notcontains $ext) { [void]$errors.Add("unsupported file type '$ext' (use .ps1, .sh or .py)") }
    $text = [System.IO.File]::ReadAllText($file, $utf8)
    if ($text.Length -gt 204800) { [void]$warns.Add('the script is larger than 200 KB; split it or justify it') }
    $nonAscii = [regex]::IsMatch($text, '[^\u0000-\u007F]')
    if ($nonAscii -and $ext -eq '.ps1') { [void]$errors.Add('non-ASCII characters: Windows PowerShell 5.1 would misread the file') }
    elseif ($nonAscii) { [void]$warns.Add('non-ASCII characters in the script') }

    if ($ext -eq '.ps1') {
        $tokens = $null; $perr = $null
        [void][System.Management.Automation.Language.Parser]::ParseFile($file, [ref]$tokens, [ref]$perr)
        if ($perr -and $perr.Count -gt 0) { [void]$errors.Add("does not parse: $($perr[0].Message)") }
        if ($text -notmatch '(?s)<#.*?\.SYNOPSIS.*?#>') { [void]$errors.Add('no comment-based help with .SYNOPSIS') }
        $code = [regex]::Replace($text, '(?s)<#.*?#>', '')
        $code = [regex]::Replace($code, '(?m)^\s*#.*$', '')
    }
    else {
        $head = ($text -split "\r?\n" | Select-Object -First 15) -join "`n"
        if ($head -notmatch '(?i)purpose\s*:') { [void]$errors.Add("no 'Purpose:' line in the first 15 lines") }
        [void]$warns.Add('syntax of this file type is not checked by the tool; run the self-test')
        $code = [regex]::Replace($text, '(?m)^\s*#.*$', '')
    }

    $forbidden = @(
        @{ P = '\bInvoke-Expression\b|(?<![\w-])iex(?![\w-])'; M = 'Invoke-Expression / iex is not allowed' },
        @{ P = '-EncodedCommand|-enc\s'; M = 'encoded commands are not allowed' },
        @{ P = 'Set-ExecutionPolicy'; M = 'changing the execution policy is not allowed' },
        @{ P = 'Add-MpPreference|Set-MpPreference'; M = 'changing antivirus settings is not allowed' },
        @{ P = '\|\s*(sh|bash)\b'; M = 'piping into a shell is not allowed' },
        @{ P = '(?<![\w.-])(eval|exec)\s*\('; M = 'eval or exec of dynamic text is not allowed' }
    )
    foreach ($f in $forbidden) { if ($code -match $f.P) { [void]$errors.Add($f.M) } }
    $secrets = @('\b(AKIA|ASIA)[0-9A-Z]{16}\b', '-----BEGIN (RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY', '\bgh[pousr]_[A-Za-z0-9]{36,}\b', '(?i)\b(password|secret|token|api[_-]?key)\b[''"]?\s*[:=]\s*[''"][^''"\s$]{8,}[''"]')
    foreach ($p in $secrets) { if ($text -match $p) { [void]$errors.Add('looks like a secret inside the script') ; break } }

    $rules = @(
        @{ Flag = 'network'; P = 'Invoke-WebRequest|Invoke-RestMethod|(?<![\w-])(iwr|irm)(?![\w-])|Net\.WebClient|HttpClient|(?<![\w.-])(curl|wget)(?![\w-])|Start-BitsTransfer|DownloadFile|Test-NetConnection|Sockets\.' },
        @{ Flag = 'destructive'; P = 'Remove-Item|(?<![\w.-])(rm|rmdir|del|erase|rd)\s+-?|Clear-Content|Format-Volume' },
        @{ Flag = 'writesOutside'; P = 'HKLM:|HKCU:|\$env:SystemRoot|\$env:ProgramFiles|\$env:windir|New-ItemProperty|Set-ItemProperty' },
        @{ Flag = 'needsAdmin'; P = 'RunAs|-Verb\s+RunAs|Set-Service|New-Service|schtasks|(?<![\w.-])sc\.exe' }
    )
    $flagParam = @{ network = '-Network'; destructive = '-Destructive'; writesOutside = '-WritesOutside'; needsAdmin = '-NeedsAdmin' }
    foreach ($r in $rules) {
        if ($code -match $r.P) {
            $detected[$r.Flag] = $true
            if (-not $declared[$r.Flag]) { [void]$errors.Add("uses something that needs the flag $($flagParam[$r.Flag]) but it is not declared") }
        }
        elseif ($declared[$r.Flag]) { [void]$warns.Add("flag $($flagParam[$r.Flag]) is declared but no matching use was detected") }
    }
    return @{ Errors = @($errors); Warnings = @($warns); Detected = $detected }
}

function Show-Lint($r, [string]$file) {
    "Lint of ${file}:"
    foreach ($e in $r.Errors) { "  ERROR  $e" }
    foreach ($w in $r.Warnings) { "  WARN   $w" }
    if ($r.Errors.Count -eq 0) { '  no errors' }
}

function Require-Approval {
    if ($ApprovedBy.Trim().Length -lt 8) { throw 'Give -ApprovedBy with the user''s approval and the date, or "policy:auto, <date>".' }
}

$lib = Get-Lib $skillRoot
$declared = @{ network = $Network.IsPresent; destructive = $Destructive.IsPresent; writesOutside = $WritesOutside.IsPresent; needsAdmin = $NeedsAdmin.IsPresent }
$entries = @(Read-Entries $lib)
$today = Get-Date -Format 'yyyy-MM-dd'

switch ($Action) {
    'List' {
        if ($entries.Count -eq 0) { 'The library is empty.'; exit 0 }
        $entries | ForEach-Object {
            $f = @(); if ($_.flags.network) { $f += 'network' }; if ($_.flags.writesOutside) { $f += 'writes-outside' }; if ($_.flags.destructive) { $f += 'destructive' }; if ($_.flags.needsAdmin) { $f += 'admin' }
            [pscustomobject]@{ Id = $_.id; File = $_.file; Version = $_.version; Platforms = (@($_.platforms) -join ','); Steps = (@($_.steps) -join ','); Flags = $(if ($f.Count) { $f -join ',' } else { '-' }); Purpose = $_.purpose }
        } | Format-Table -AutoSize -Wrap | Out-String -Width 220
        exit 0
    }
    'Find' {
        if (-not $Query.Trim()) { throw 'Give -Query "words".' }
        $words = @($Query.ToLower() -split '\s+' | Where-Object { $_ })
        $hay = { param($e) ((@($e.file, $e.purpose) + @($e.platforms) + @($e.steps) + @($e.tags)) -join ' ').ToLower() }
        $all = @($entries | Where-Object { $h = & $hay $_; (@($words | Where-Object { $h.Contains($_) }).Count -eq $words.Count) })
        $any = @()
        if ($all.Count -eq 0) { $any = @($entries | Where-Object { $h = & $hay $_; (@($words | Where-Object { $h.Contains($_) }).Count -gt 0) }) }
        $hits = if ($all.Count -gt 0) { $all } else { $any }
        if ($hits.Count -eq 0) { "No library script matches '$Query'. Write a new one, and consider proposing it for the library (references/library-policy.md)."; exit 1 }
        if ($all.Count -eq 0) { 'Partial matches only:' }
        $hits | ForEach-Object { "{0}  {1}  v{2}  [{3}]  steps {4}: {5}" -f $_.id, $_.file, $_.version, (@($_.platforms) -join ','), (@($_.steps) -join ','), $_.purpose }
        exit 0
    }
    'Lint' {
        if (-not $Path) { throw 'Give -Path <script>.' }
        $r = Test-Script $Path $declared
        Show-Lint $r $Path
        if ($r.Errors.Count -gt 0) { exit 1 }
        exit 0
    }
    'Add' {
        if (-not $Path) { throw 'Give -Path <script>.' }
        if (-not $Purpose.Trim()) { throw 'Give -Purpose (why the script helps future builds).' }
        if (-not $Test.Trim()) { throw 'Give -Test (the arguments that make the script run its own self-test and exit 0, for example -Selftest).' }
        Require-Approval
        if ($ApprovedBy -match '(?i)^policy:auto' -and ($Network -or $WritesOutside -or $Destructive -or $NeedsAdmin)) {
            throw 'The automatic policy cannot save a script that uses the network, writes outside the project, is destructive or needs administrator rights. Ask the user.'
        }
        $r = Test-Script $Path $declared
        Show-Lint $r $Path
        if ($r.Errors.Count -gt 0) { Write-Output 'Not added: fix the errors.'; exit 1 }
        $file = if ($Name) { $Name } else { Split-Path -Leaf $Path }
        if ($file -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]*$' -or @('.ps1', '.sh', '.py') -notcontains [System.IO.Path]::GetExtension($file).ToLower()) { throw "Invalid script name '$file' (letters, digits, . _ - ; extension .ps1, .sh or .py)." }
        if (@($entries | Where-Object { $_.file -eq $file }).Count -gt 0) { throw "A script named $file is already registered. Use -Action Update." }
        $max = 0; foreach ($e in $entries) { if ($e.id -match '^LIB-(\d+)$') { $n = [int]$Matches[1]; if ($n -gt $max) { $max = $n } } }
        $newId = 'LIB-{0:D3}' -f ($max + 1)
        [void](New-Item -ItemType Directory -Path $lib.Scripts -Force)
        $target = Join-Path $lib.Scripts $file
        Copy-Item -LiteralPath $Path -Destination $target -Force
        $ver = if ($Version) { $Version } else { '1.0.0' }
        $entry = [pscustomobject]@{
            id = $newId; file = $file; version = $ver; purpose = $Purpose.Trim()
            steps = @(Split-List $Steps); platforms = @(Split-List $Platforms); tags = @(Split-List $Tags)
            test = $Test.Trim()
            flags = [pscustomobject]@{ network = $declared.network; writesOutside = $declared.writesOutside; destructive = $declared.destructive; needsAdmin = $declared.needsAdmin }
            sha256 = (Get-Hash $target); added = $today; updated = $today; source = $Source; approvedBy = $ApprovedBy.Trim()
            history = @([pscustomobject]@{ version = $ver; date = $today; note = 'added'; approvedBy = $ApprovedBy.Trim() })
        }
        Write-Entries $lib (@($entries) + @($entry))
        "Added $newId ($file, version $ver) to $($lib.Dir)"
        Sync-Mirror $skillRoot
        exit 0
    }
    'Update' {
        if (-not $Id -or -not $Path) { throw 'Give -Id and -Path <new version of the script>.' }
        Require-Approval
        if ($ApprovedBy -match '(?i)^policy:auto' -and ($Network -or $WritesOutside -or $Destructive -or $NeedsAdmin)) { throw 'The automatic policy cannot save this kind of script. Ask the user.' }
        $cur = @($entries | Where-Object { $_.id -eq $Id })
        if ($cur.Count -ne 1) { throw "No entry $Id." }
        $e = $cur[0]
        # an update keeps the flags unless new ones are declared
        $dec = @{ network = ($declared.network -or [bool]$e.flags.network); destructive = ($declared.destructive -or [bool]$e.flags.destructive); writesOutside = ($declared.writesOutside -or [bool]$e.flags.writesOutside); needsAdmin = ($declared.needsAdmin -or [bool]$e.flags.needsAdmin) }
        $r = Test-Script $Path $dec
        Show-Lint $r $Path
        if ($r.Errors.Count -gt 0) { Write-Output 'Not updated: fix the errors.'; exit 1 }
        $target = Join-Path $lib.Scripts $e.file
        Copy-Item -LiteralPath $Path -Destination $target -Force
        if ($Version) { $ver = $Version } else { $p = ([string]$e.version).Split('.'); if ($p.Count -eq 3) { $ver = "$($p[0]).$($p[1]).$([int]$p[2] + 1)" } else { $ver = ([string]$e.version) + '.1' } }
        $e.version = $ver; $e.sha256 = (Get-Hash $target); $e.updated = $today
        if ($Purpose.Trim()) { $e.purpose = $Purpose.Trim() }
        if ($Test.Trim()) { $e.test = $Test.Trim() }
        $e.flags = [pscustomobject]@{ network = $dec.network; writesOutside = $dec.writesOutside; destructive = $dec.destructive; needsAdmin = $dec.needsAdmin }
        $note = if ($Purpose.Trim()) { 'updated: ' + $Purpose.Trim() } else { 'updated' }
        $e.history = @($e.history) + @([pscustomobject]@{ version = $ver; date = $today; note = $note; approvedBy = $ApprovedBy.Trim() })
        Write-Entries $lib $entries
        "Updated $Id to version $ver"
        Sync-Mirror $skillRoot
        exit 0
    }
    'Check' {
        $bad = 0
        $known = @{}
        foreach ($e in $entries) {
            if (-not $e.file) { continue }
            if ($Id -and $e.id -ne $Id) { continue }
            $known[$e.file] = $true
            $f = Join-Path $lib.Scripts $e.file
            if (-not (Test-Path -LiteralPath $f)) { "MISSING       $($e.id) $($e.file)"; $bad++; continue }
            if ((Get-Hash $f) -ne $e.sha256) { "MODIFIED      $($e.id) $($e.file): the content differs from what was approved; do not run it, tell the user"; $bad++; continue }
            "OK            $($e.id) $($e.file) v$($e.version)"
        }
        if (-not $Id -and (Test-Path -LiteralPath $lib.Scripts)) {
            foreach ($f in @(Get-ChildItem -LiteralPath $lib.Scripts -File)) {
                if (-not $known.ContainsKey($f.Name)) { "UNREGISTERED  $($f.Name): not in the registry; do not run it, tell the user"; $bad++ }
            }
        }
        if ($entries.Count -eq 0 -and $bad -eq 0) { 'The library is empty; nothing to check.' }
        if ($bad -gt 0) { "$bad problem(s)."; exit 1 }
        exit 0
    }
    'Test' {
        $failed = 0; $ran = 0
        foreach ($e in $entries) {
            if ($Id -and $e.id -ne $Id) { continue }
            $f = Join-Path $lib.Scripts $e.file
            if (-not (Test-Path -LiteralPath $f)) { "MISSING  $($e.id) $($e.file)"; $failed++; continue }
            if ((Get-Hash $f) -ne $e.sha256) { "MODIFIED $($e.id) $($e.file): not run, tell the user"; $failed++; continue }
            $ext = [System.IO.Path]::GetExtension($f).ToLower()
            if ($ext -ne '.ps1') { "SKIPPED  $($e.id) $($e.file): self-tests of $ext files are run by hand" ; continue }
            $testArgs = @($e.test -split '\s+' | Where-Object { $_ })
            $out = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $f @testArgs
            $code = $LASTEXITCODE
            $ran++
            if ($code -eq 0) { "PASS     $($e.id) $($e.file)" } else { "FAIL     $($e.id) $($e.file) (exit $code)"; ($out | Select-Object -First 8); $failed++ }
        }
        if ($ran -eq 0 -and $failed -eq 0) { 'No self-test was run.' }
        if ($failed -gt 0) { exit 1 }
        exit 0
    }
    'Export' {
        if (-not $Id -or -not $Dest) { throw 'Give -Id and -Dest <path of the other sdf-flow folder>.' }
        if (-not (Test-Path -LiteralPath (Join-Path $Dest 'SKILL.md'))) { throw "Not an sdf-flow folder (no SKILL.md): $Dest" }
        $cur = @($entries | Where-Object { $_.id -eq $Id })
        if ($cur.Count -ne 1) { throw "No entry $Id." }
        $e = $cur[0]
        $src = Join-Path $lib.Scripts $e.file
        if (-not (Test-Path -LiteralPath $src) -or (Get-Hash $src) -ne $e.sha256) { throw "$($e.file) is missing or modified; run -Action Check first." }
        $dLib = Get-Lib (Resolve-Path -LiteralPath $Dest).Path
        $dEntries = @(Read-Entries $dLib)
        $same = @($dEntries | Where-Object { $_.file -eq $e.file })
        if ($same.Count -gt 0 -and $same[0].sha256 -eq $e.sha256) { "Already present in the destination with the same content: $($same[0].id)"; exit 0 }
        if ($same.Count -gt 0 -and -not $Force) { throw "The destination has a different $($e.file) (version $($same[0].version)). Use -Force to replace it." }
        [void](New-Item -ItemType Directory -Path $dLib.Scripts -Force)
        Copy-Item -LiteralPath $src -Destination (Join-Path $dLib.Scripts $e.file) -Force
        $copy = $e | ConvertTo-Json -Depth 8 | ConvertFrom-Json
        if ($same.Count -gt 0) { $copy.id = $same[0].id; $dEntries = @($dEntries | Where-Object { $_.file -ne $e.file }) }
        else {
            $max = 0; foreach ($x in $dEntries) { if ($x.id -match '^LIB-(\d+)$') { $n = [int]$Matches[1]; if ($n -gt $max) { $max = $n } } }
            $copy.id = 'LIB-{0:D3}' -f ($max + 1)
        }
        Write-Entries $dLib (@($dEntries) + @($copy))
        "Exported $Id as $($copy.id) to $($dLib.Dir)"
        Sync-Mirror $dLib.Root
        exit 0
    }
    'Remove' {
        if (-not $Id) { throw 'Give -Id.' }
        Require-Approval
        $cur = @($entries | Where-Object { $_.id -eq $Id })
        if ($cur.Count -ne 1) { throw "No entry $Id." }
        $f = Join-Path $lib.Scripts $cur[0].file
        if (Test-Path -LiteralPath $f) { Remove-Item -LiteralPath $f -Force }
        Write-Entries $lib @($entries | Where-Object { $_.id -ne $Id })
        "Removed $Id ($($cur[0].file))"
        Sync-Mirror $skillRoot
        exit 0
    }
}
